from __future__ import annotations

import pprint
from pathlib import Path
from typing import Any

from agents.decorators import tool

from ..shared import AwsToolConfig, json_dumps, safe_markdown_name


def _write_considered_actions(path: Path, actions: list[dict[str, Any]]) -> None:
    rendered_actions = pprint.pformat(actions, width=120, sort_dicts=True)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        '"""Candidate AWS optimization actions generated by the cost agent.\n\n'
        "This file is review material only. It is not executed automatically.\n"
        '"""\n\n'
        f"CONSIDERED_ACTIONS = {rendered_actions}\n",
        encoding="utf-8",
    )


def prepare_output_dirs(config: AwsToolConfig) -> None:
    """Create output folders and reset per-run action artifacts."""
    config.assessment_dir.mkdir(parents=True, exist_ok=True)
    config.optimization_script_dir.mkdir(parents=True, exist_ok=True)
    config.tools_dir.mkdir(parents=True, exist_ok=True)
    config.proposed_tools_path.touch(exist_ok=True)
    _write_considered_actions(config.optimization_script_dir / "considered_actions.py", [])


def create_artifact_tools(config: AwsToolConfig) -> list[Any]:
    """Create local artifact tools for assessments, tool proposals, and candidate actions."""
    considered_actions: list[dict[str, Any]] = []

    @tool
    def read_tools_registry() -> str:
        """Read tools/tools.md, the source-of-truth registry of tools available to this agent."""
        if not config.tools_registry_path.exists():
            return json_dumps({"ok": False, "error": "tools/tools.md does not exist."})

        return config.tools_registry_path.read_text(encoding="utf-8")

    @tool
    def write_assessment_file(filename: str, markdown: str) -> str:
        """Write a markdown assessment file under the assessment folder.

        Args:
            filename: File name, not a path. The tool normalizes it to a safe .md file.
            markdown: Markdown report body.
        """
        output_path = config.assessment_dir / safe_markdown_name(filename)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(markdown, encoding="utf-8")

        return json_dumps({"ok": True, "path": str(output_path)})

    @tool
    def record_proposed_tool(tool_name: str, reason: str, aws_apis: list[str], proposed_interface: str) -> str:
        """Append a missing tool proposal to tools/proposed_tools.md.

        Args:
            tool_name: Proposed function tool name.
            reason: Why the existing tools are insufficient.
            aws_apis: AWS APIs or data sources the tool would call.
            proposed_interface: Proposed inputs and outputs for the tool.
        """
        config.proposed_tools_path.parent.mkdir(parents=True, exist_ok=True)
        with config.proposed_tools_path.open("a", encoding="utf-8") as file:
            file.write(
                f"\n## {tool_name}\n\n"
                f"- Reason: {reason}\n"
                f"- AWS APIs: {', '.join(aws_apis)}\n"
                f"- Proposed interface: {proposed_interface}\n"
            )

        return json_dumps({"ok": True, "path": str(config.proposed_tools_path)})

    @tool
    def stage_change_plan(
        recommendation_id: str,
        service: str,
        proposed_action: str,
        expected_savings: str,
        risk: str,
        validation_plan: list[str],
        rollback_plan: list[str],
        region: str | None = None,
        resource_ids: list[str] | None = None,
        implementation_notes: str | None = None,
    ) -> str:
        """Stage a proposed AWS change in optmization_script/considered_actions.py without changing AWS resources."""
        action = {
            "recommendation_id": recommendation_id,
            "service": service,
            "region": region,
            "resource_ids": resource_ids or [],
            "proposed_action": proposed_action,
            "expected_savings": expected_savings,
            "risk": risk,
            "validation_plan": validation_plan,
            "rollback_plan": rollback_plan,
            "implementation_notes": implementation_notes,
            "requires_human_approval": True,
            "mutation_enabled": config.enable_mutations,
        }
        considered_actions.append(action)
        path = config.optimization_script_dir / "considered_actions.py"
        _write_considered_actions(path, considered_actions)

        return json_dumps(
            {
                "ok": True,
                "staged_only": True,
                "path": str(path),
                "message": "Change plan written for review. No AWS resources were changed.",
                "change_plan": action,
            }
        )

    return [read_tools_registry, write_assessment_file, record_proposed_tool, stage_change_plan]
